services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: quantix
      POSTGRES_DB: quantix
    volumes:
      - quantix_pg:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d quantix"]
      interval: 2s
      timeout: 2s
      retries: 15

  api:
    build:
      context: ./quantix-api
      dockerfile: Dockerfile.dev
    env_file: ./quantix-api/.env
    environment:
      # Estas van en la API, no en db
      SEED_ON_START: "1"
      SEED_ADMIN_EMAIL: admin@quantix.local
      SEED_ADMIN_PASSWORD: "1234"
    ports:
      - "3001:3000"
      - "5555:5555"
    volumes:
      - ./quantix-api:/app
      - /app/node_modules
    depends_on:
      db:
        condition: service_healthy
    command: ["/bin/sh", "./docker/dev.entrypoint.sh"]

  frontend:
    build:
      context: ./quantix-web
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./quantix-web:/app:delegated
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    depends_on:
      - api
    command: npm run dev -- --host

volumes:
  quantix_pg: {}
